@base_url = http://localhost:8080/api/user
# create happy path
POST {{base_url}} HTTP/1.1
Content-Type: application/json

{
  "email": "c@c.com",
  "password": "c"
}

### create blank email unhappy path
POST {{base_url}} HTTP/1.1
Content-Type: application/json

{
  "email": "",
  "password": "c"
}

### create blank password unhappy path
POST {{base_url}} HTTP/1.1
Content-Type: application/json

{
  "email": "c@c.com",
  "password": ""
}


### create duplicate email unhappy path
POST {{base_url}} HTTP/1.1
Content-Type: application/json

{
  "email": "c@c.com",
  "password": "c"
}

###  login happy path
POST {{base_url}}/login
Content-Type: application/json

{
  "email": "c@c.com",
  "password": "c"
}

### login user not found
POST {{base_url}}/login
Content-Type: application/json

{
  "email": "z@z.com",
  "password": "z"
}

### login wrong password
POST {{base_url}}/login
Content-Type: application/json

{
  "email": "c@c.com",
  "password": "z"
}